"""initial version

Revision ID: 1748ce18f7f1
Revises: 
Create Date: 2024-09-25 13:03:16.705692+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1748ce18f7f1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "caller",
        sa.Column("caller_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Unicode(length=100), nullable=False),
        sa.Column("idp_id", sa.Unicode(length=100), nullable=False),
        sa.Column("email", sa.Unicode(length=100), nullable=False),
        sa.Column("first_created", sa.DateTime(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("caller_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("idp_id"),
    )
    op.create_table(
        "chat",
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("caller_id", sa.Uuid(), nullable=False),
        sa.Column("caller_session_id", sa.Unicode(length=50), nullable=False),
        sa.Column("caller_chat_text", sa.Text(), nullable=False),
        sa.Column(
            "caller_attachment_type",
            sa.Enum("TEXT_FILE", "PDF_FILE", "AUDIO_FILE", name="attachmenttype"),
            nullable=True,
        ),
        sa.Column("caller_attachment_bytes", sa.LargeBinary(), nullable=True),
        sa.Column("prompt_template", sa.Text(), nullable=True),
        sa.Column(
            "inference_provider_type",
            sa.Enum(
                "KUBERNETES_POD", "RUNPOD_SERVERLESS_API", name="inferenceprovidertype"
            ),
            nullable=False,
        ),
        sa.Column(
            "inference_provider_request_id", sa.Unicode(length=50), nullable=True
        ),
        sa.Column("response_chat_text", sa.Text(), nullable=True),
        sa.Column(
            "response_attachment_type",
            sa.Enum("TEXT_FILE", "PDF_FILE", "AUDIO_FILE", name="attachmenttype"),
            nullable=True,
        ),
        sa.Column("response_attachment_bytes", sa.LargeBinary(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("inference_duration_seconds", sa.Float(), nullable=True),
        sa.Column("total_duration_seconds", sa.Float(), nullable=True),
        sa.Column("first_created", sa.DateTime(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["caller_id"],
            ["caller.caller_id"],
        ),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat")
    op.drop_table("caller")
    # ### end Alembic commands ###
